name: auto release for windows

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build
      run: |
        pyinstaller ./ui.pyw -F -w
        mv ./dist/ui ./dist/ui.exe
        cp ./ico.ico ./dist/ico.ico
        cp ./ui.qss ./dist/ui.qss
        ls ./dist -l
        tar -cvf ctp.tar ./dist/ui.exe ./dist/ui.qss ./dist/ico.ico
    - name: changeLog
      run: |
        echo "Generate by Github action, please download ctp.tar and unpack it with 7z or winrar,then you can run ui.exe." > change.log
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        # GitHub secret token 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        # Git tag (for automatic releases)
        automatic_release_tag: "latest"
        # Should this release be marked as a draft?
        draft: false
        # Should this release be marked as a pre-release?
        prerelease: true
        # Release title (for automatic releases)
        title: "auto published"
        # Assets to upload to the release
        files: |
          ./ctp.tar
